import type { KnowledgeDocument } from './types';

export const knowledgeBase: KnowledgeDocument[] = [
  {
    id: 'tenant-security-deposit',
    title: 'Security Deposit Return in Rental Agreements',
    authority: 'State Rent Control Acts / Civil Courts',
    category: 'Tenant/Housing',
    jurisdiction: 'India (varies by state)',
    summary:
      'When a tenant vacates a rented property, the landlord is generally expected to return the security deposit after deducting legitimate unpaid rent or verified damages. There is no single central law governing security deposits — the rules vary by state and by the terms of the rental agreement.',
    eligibility: [
      'The tenant must have vacated the property',
      'There should be no major unpaid rent or verified damages',
      'The rental agreement should have been in place',
    ],
    procedure: [
      'Send a written request to the landlord asking for the deposit return',
      'Wait for a reasonable period (typically 15–30 days)',
      'If no response, send a formal legal notice through a lawyer',
      'File a complaint in the Rent Controller / Civil Court if unresolved',
    ],
    required_documents: [
      'Rental agreement / lease deed',
      'Payment receipts for rent and deposit',
      'Written communication with landlord (messages, emails, letters)',
      'Evidence of vacating (handover note, key return receipt)',
      'Photos of the property condition at handover',
    ],
    important_notes: [
      'There is no fixed national deadline for deposit return — check your state rent act and your rental agreement',
      'Landlords can deduct for unpaid rent and genuine damages, but not for normal wear and tear',
      'Keep all communication in writing — verbal promises are hard to prove',
    ],
    official_source: 'State Rent Control Acts; Civil Procedure Code',
    source_url: 'https://www.india.gov.in',
    last_verified: '2026-01-15',
    keywords: ['security deposit', 'landlord', 'rent', 'tenant', 'rental', 'lease', 'vacate', 'refund', 'deposit return'],
  },
  {
    id: 'consumer-defective-product',
    title: 'Consumer Rights for Defective Products',
    authority: 'Consumer Protection Act, 2019',
    category: 'Consumer Rights',
    jurisdiction: 'India',
    summary:
      'Under the Consumer Protection Act, 2019, a consumer who purchases a product that is defective, not as described, or unsafe has the right to seek a replacement, refund, or compensation. The seller cannot disclaim liability for inherent defects.',
    eligibility: [
      'The product must have a defect or deficiency',
      'The complaint should be filed within 2 years of the issue arising',
      'The buyer must be a consumer (purchased for personal use, not resale)',
    ],
    procedure: [
      'Collect proof of purchase (bill, invoice, warranty card)',
      'Send a written complaint to the seller/manufacturer',
      'Wait for a reasonable response (typically 2–4 weeks)',
      'If unresolved, file a complaint with the Consumer Forum (District/State/National based on claim value)',
      'Can also file online through the Consumer Helpline or e-Daakhil portal',
    ],
    required_documents: [
      'Purchase bill / invoice',
      'Warranty card / guarantee document',
      'Photos or evidence of the defect',
      'Communication with seller (emails, messages, complaint numbers)',
      'Bank statement showing the payment',
    ],
    important_notes: [
      'District Consumer Forum handles claims up to ₹50 lakh',
      'State Commission handles claims between ₹50 lakh and ₹2 crore',
      'National Commission handles claims above ₹2 crore',
      'e-Daakhil allows online filing of consumer complaints',
    ],
    official_source: 'Consumer Protection Act, 2019',
    source_url: 'https://consumerhelpline.gov.in',
    last_verified: '2026-01-20',
    keywords: ['defective', 'product', 'consumer', 'seller', 'refund', 'replacement', 'warranty', 'complaint', 'purchase'],
  },
  {
    id: 'rti-road-repair-funds',
    title: 'RTI for Road Repair and Infrastructure Spending',
    authority: 'Right to Information Act, 2005',
    category: 'RTI',
    jurisdiction: 'India',
    summary:
      'Any citizen can file an RTI application to request information from a public authority about how public funds were spent, including road repair budgets, contracts awarded, and project timelines. The Public Information Officer (PIO) must respond within 30 days.',
    eligibility: [
      'Any Indian citizen can file an RTI application',
      'The information must be held by a public authority',
      'Application fee (₹10 for central government, varies by state) must be paid',
    ],
    procedure: [
      'Identify the correct public authority (e.g., Public Works Department, Municipality, Panchayat)',
      'Write the RTI application with clear, specific questions',
      'Pay the application fee (₹10 for central; varies by state)',
      'Submit to the PIO of the relevant department',
      'Receive a response within 30 days (48 hours if life/liberty involved)',
      'If no response or unsatisfied, file first appeal within 30 days',
    ],
    required_documents: [
      'Proof of identity (Aadhaar, PAN, Voter ID)',
      'Application fee receipt',
      'Copy of the RTI application',
      'Speed post / courier receipt for submission proof',
    ],
    important_notes: [
      'RTI applications can be filed online through the central RTI portal for central government departments',
      'State governments have their own RTI portals and fee structures',
      'Some information is exempt under Section 8 of the RTI Act (e.g., national security, personal information of third parties)',
      'If the PIO does not respond in 30 days, you can file a first appeal',
    ],
    official_source: 'Right to Information Act, 2005',
    source_url: 'https://rti.gov.in',
    last_verified: '2026-02-01',
    keywords: ['rti', 'right to information', 'road', 'repair', 'funds', 'public authority', 'pio', 'information', 'government spending', 'infrastructure'],
  },
  {
    id: 'welfare-scheme-general',
    title: 'Government Welfare Schemes — General Eligibility',
    authority: 'Ministry of Rural Development / State Governments',
    category: 'Welfare Schemes',
    jurisdiction: 'India',
    summary:
      'The Government of India and state governments run various welfare schemes for income support, housing, employment, food security, and healthcare. Eligibility depends on age, income, occupation, family composition, and state of residence. Each scheme has its own criteria.',
    eligibility: [
      'Indian citizen',
      'Meets income criteria (varies by scheme)',
      'Meets category criteria (BPL, SC/ST, OBC, elderly, widow, disabled, etc.)',
      'Resident of the relevant state/UT',
    ],
    procedure: [
      'Identify the relevant scheme through official portals',
      'Check eligibility criteria on the scheme portal',
      'Gather required documents',
      'Apply online or at the designated office (Common Service Centre, Panchayat, Block office)',
      'Track application status online',
    ],
    required_documents: [
      'Aadhaar card',
      'Income certificate',
      'Caste certificate (if applicable)',
      'Residence proof',
      'Bank passbook / account details',
      'Ration card',
      'Photographs',
    ],
    important_notes: [
      'Eligibility is ultimately decided by the concerned government department, not by any third-party app',
      'Many schemes require Aadhaar linkage',
      'Some schemes are applied through Common Service Centres (CSC)',
      'Always verify scheme details on the official government portal',
    ],
    official_source: 'Government of India Welfare Schemes Portal',
    source_url: 'https://www.mygov.in',
    last_verified: '2026-01-10',
    keywords: ['welfare', 'scheme', 'government', 'eligibility', 'subsidy', 'benefit', 'bpl', 'rural', 'poor', 'assistance'],
  },
  {
    id: 'public-grievance-portal',
    title: 'Filing a Public Grievance through CPGRAMS',
    authority: 'Department of Administrative Reforms & Public Grievances',
    category: 'Public Grievance',
    jurisdiction: 'India',
    summary:
      'The Centralized Public Grievance Redress and Monitoring System (CPGRAMS) allows citizens to file complaints against any central government department or ministry. State governments have their own grievance portals. Grievances are typically acknowledged within 3 days and resolved within 30 days.',
    eligibility: [
      'Any Indian citizen can file a grievance',
      'The grievance must relate to a government service or department',
      'The issue should not be sub-judice (before a court)',
    ],
    procedure: [
      'Register on the CPGRAMS portal (pgportal.gov.in)',
      'Select the ministry/department concerned',
      'Describe the grievance clearly with dates and details',
      'Upload supporting documents',
      'Receive a unique registration number for tracking',
      'Track status and expect resolution within 30 days',
    ],
    required_documents: [
      'Proof of identity',
      'Supporting documents related to the grievance',
      'Previous correspondence with the department (if any)',
      'Reference numbers of earlier complaints (if any)',
    ],
    important_notes: [
      'CPGRAMS is for central government grievances; state issues go to state portals',
      'You can escalate if the grievance is not resolved',
      'Keep your grievance registration number for follow-up',
    ],
    official_source: 'CPGRAMS — pgportal.gov.in',
    source_url: 'https://pgportal.gov.in',
    last_verified: '2026-01-25',
    keywords: ['grievance', 'complaint', 'government', 'cpgrams', 'pgportal', 'public service', 'redressal', 'citizen'],
  },
  {
    id: 'workplace-unpaid-wages',
    title: 'Unpaid Wages and Workplace Rights',
    authority: 'Payment of Wages Act, 1936; Labour Codes',
    category: 'Workplace',
    jurisdiction: 'India',
    summary:
      'An employee who has not been paid wages, overtime, or final settlement has the right to file a complaint with the Labour Commissioner. Employers cannot withhold earned wages. The new Labour Codes consolidate several older laws.',
    eligibility: [
      'The person must be an employee (formal or informal sector)',
      'Wages must be due and unpaid',
      'The complaint should be filed within the limitation period',
    ],
    procedure: [
      'Send a written demand to the employer for unpaid wages',
      'Keep proof of employment and attendance',
      'File a complaint with the Labour Commissioner',
      'Attend conciliation proceedings',
      'If unresolved, approach the Labour Court',
    ],
    required_documents: [
      'Employment letter / contract',
      'Salary slips / bank statements',
      'Attendance records',
      'Communication with employer',
      'ID proof',
    ],
    important_notes: [
      'The Labour Commissioner can order payment of due wages',
      'Informal sector workers can also approach the Labour Commissioner',
      'The limitation period varies by the nature of the claim',
    ],
    official_source: 'Payment of Wages Act, 1936; Labour Codes',
    source_url: 'https://labour.gov.in',
    last_verified: '2026-01-18',
    keywords: ['wages', 'salary', 'unpaid', 'employer', 'workplace', 'labour', 'labour commissioner', 'overtime', 'settlement'],
  },
  {
    id: 'education-admission-grievance',
    title: 'Education Admission and Fee Refund Grievances',
    authority: 'State Education Departments; UGC / AICTE / CBSE',
    category: 'Education',
    jurisdiction: 'India',
    summary:
      'Students and parents can file grievances about unfair admission practices, non-refund of fees, or harassment in schools and colleges. Regulatory bodies like UGC, AICTE, and CBSE have online grievance redressal mechanisms.',
    eligibility: [
      'The student or parent must be affected by the institution action',
      'The institution should be recognized by a regulatory body',
      'Internal grievance mechanism should be attempted first',
    ],
    procedure: [
      'File a written complaint with the institution head',
      'If unresolved, approach the regulatory body (UGC/AICTE/CBSE/state board)',
      'Use the online grievance portal of the concerned regulator',
      'Escalate to the Department of Education if needed',
    ],
    required_documents: [
      'Admission letter / fee receipt',
      'Communication with the institution',
      'Relevant prospectus / brochure',
      'ID proof of the student',
    ],
    important_notes: [
      'UGC has an online grievance redressal portal for higher education',
      'AICTE handles technical education grievances',
      'CBSE has a grievance portal for school-related issues',
    ],
    official_source: 'UGC / AICTE / CBSE Grievance Portals',
    source_url: 'https://www.ugc.gov.in',
    last_verified: '2026-01-12',
    keywords: ['education', 'school', 'college', 'admission', 'fee', 'refund', 'student', 'teacher', 'university', 'grievance'],
  },
  {
    id: 'banking-unauthorized-charges',
    title: 'Banking — Unauthorized Charges and Account Grievances',
    authority: 'Reserve Bank of India (RBI)',
    category: 'Banking/Financial Services',
    jurisdiction: 'India',
    summary:
      'If a bank levies unauthorized charges, freezes an account without notice, or fails to resolve a transaction dispute, the customer can file a complaint under the Banking Ombudsman Scheme. The bank must first be given 30 days to resolve the issue.',
    eligibility: [
      'The customer must have a banking relationship',
      'A written complaint must have been filed with the bank first',
      '30 days must have passed without resolution (or unsatisfactory response)',
    ],
    procedure: [
      'File a written complaint with the bank branch and get a complaint number',
      'Wait 30 days for resolution',
      'If unresolved, file a complaint with the Banking Ombudsman',
      'The Ombudsman can award compensation up to ₹20 lakh and loss up to ₹1 lakh',
      'Can also file online through the RBI Ombudsman portal',
    ],
    required_documents: [
      'Bank statement showing the disputed transaction',
      'Complaint number and bank response (or proof of no response)',
      'Account details',
      'ID proof',
    ],
    important_notes: [
      'The Banking Ombudsman is free to use — no fee required',
      'The complaint must be filed within 1 year of the bank response',
      'RBI has integrated Ombudsman schemes for banks, NBFCs, and digital transactions',
    ],
    official_source: 'Reserve Bank of India — Integrated Ombudsman Scheme',
    source_url: 'https://rbims.rbi.org.in',
    last_verified: '2026-01-22',
    keywords: ['bank', 'banking', 'unauthorized', 'charges', 'account', 'ombudsman', 'rbi', 'transaction', 'fee', 'freeze'],
  },
  {
    id: 'gov-service-delay',
    title: 'Government Service Delay — Pendency and Non-Delivery',
    authority: 'Concerned Government Department; State Grievance Portals',
    category: 'Government Services',
    jurisdiction: 'India',
    summary:
      'If a government service (passport, ration card, pension, certificate) is delayed beyond the stipulated timeline, the citizen can file a grievance with the department and escalate to higher authorities or the grievance portal.',
    eligibility: [
      'The citizen must have applied for the service',
      'The application must be within the stipulated processing time or beyond',
      'The service must be provided by a government department',
    ],
    procedure: [
      'Check the status of the application online',
      'File a grievance on the department portal or CPGRAMS',
      'Provide the application reference number',
      'Escalate to the senior officer if not resolved',
      'File an RTI to ask reasons for delay if needed',
    ],
    required_documents: [
      'Application acknowledgment / reference number',
      'Proof of application submission',
      'Previous correspondence',
      'ID proof',
    ],
    important_notes: [
      'Many states have Right to Services Acts with fixed timelines',
      'Some services have a deemed approval clause if not processed in time',
      'RTI can be used alongside a grievance to get reasons for delay',
    ],
    official_source: 'State Right to Service Acts; CPGRAMS',
    source_url: 'https://pgportal.gov.in',
    last_verified: '2026-01-28',
    keywords: ['government service', 'delay', 'pending', 'passport', 'ration card', 'pension', 'certificate', 'application', 'timeline'],
  },
];
