import type { Scheme } from './types';

export const schemes: Scheme[] = [
  {
    id: 'pmjay',
    name: 'Ayushman Bharat (PM-JAY)',
    ministry: 'Ministry of Health and Family Welfare',
    category: 'Healthcare',
    description:
      'Health insurance coverage of up to ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    eligibility: [
      { label: 'Are you an Indian citizen?', field: 'citizen', type: 'select', options: ['Yes', 'No'] },
      { label: 'What is your family income (annual)?', field: 'income', type: 'select', options: ['Below ₹2.5 lakh', '₹2.5–5 lakh', 'Above ₹5 lakh'] },
      { label: 'Are you listed in the SECC-2011 database?', field: 'secc', type: 'select', options: ['Yes', 'No', 'Not sure'] },
      { label: 'What is your occupation category?', field: 'occupation', type: 'select', options: ['Casual labour', 'Daily wage', 'Agriculture', 'Self-employed', 'Salaried', 'Unemployed'] },
    ],
    benefits: 'Health coverage up to ₹5 lakh per family per year for hospitalization at empanelled hospitals.',
    required_documents: ['Aadhaar card', 'Ration card', 'Mobile number', 'Family ID (if applicable)'],
    application_steps: [
      'Check if your family is listed in the SECC-2011 database at a CSC or hospital',
      'If eligible, visit an empanelled hospital with Aadhaar and ration card',
      'Get the PM-JAY card (Ayushman Card) issued',
      'Use the card at any empanelled hospital for cashless treatment',
    ],
    official_source: 'Ayushman Bharat PM-JAY',
    source_url: 'https://pmjay.gov.in',
    last_verified: '2026-01-15',
    keywords: ['health', 'insurance', 'ayushman', 'pmjay', 'hospital', 'medical', 'poor', 'bpl'],
  },
  {
    id: 'pmay',
    name: 'Pradhan Mantri Awas Yojana (PMAY)',
    ministry: 'Ministry of Housing and Urban Affairs / Rural Development',
    category: 'Housing',
    description:
      'Subsidized housing loans and grants for construction of pucca houses for economically weaker sections.',
    eligibility: [
      { label: 'Do you already own a pucca house?', field: 'own_house', type: 'select', options: ['Yes', 'No'] },
      { label: 'What is your annual family income?', field: 'income', type: 'select', options: ['Below ₹3 lakh (EWS)', '₹3–6 lakh (LIG)', '₹6–12 lakh (MIG-I)', 'Above ₹12 lakh'] },
      { label: 'Do you have a female family member who can co-own?', field: 'female_coowner', type: 'select', options: ['Yes', 'No'] },
      { label: 'What is your area type?', field: 'area', type: 'select', options: ['Urban', 'Rural'] },
    ],
    benefits: 'Interest subsidy on home loans up to ₹2.67 lakh; grant up to ₹1.2 lakh for construction in rural areas.',
    required_documents: ['Aadhaar card', 'Income certificate', 'Bank passbook', 'Caste/income certificate (if applicable)', 'Land documents'],
    application_steps: [
      'Apply online on the PMAY portal or through a Common Service Centre',
      'Submit income proof and identity documents',
      'Get your application verified by the local authority',
      'Receive subsidy on your home loan or grant for construction',
    ],
    official_source: 'Pradhan Mantri Awas Yojana',
    source_url: 'https://pmaymis.gov.in',
    last_verified: '2026-01-20',
    keywords: ['housing', 'house', 'home loan', 'awas', 'pmay', 'subsidy', 'construction', 'shelter'],
  },
  {
    id: 'nrega',
    name: 'MGNREGA (Rural Employment Guarantee)',
    ministry: 'Ministry of Rural Development',
    category: 'Employment',
    description:
      'Guarantees 100 days of wage employment per year to rural households with adult members willing to do unskilled manual work.',
    eligibility: [
      { label: 'What is your area type?', field: 'area', type: 'select', options: ['Rural', 'Urban'] },
      { label: 'Is any adult member willing to do unskilled manual labour?', field: 'willing_work', type: 'select', options: ['Yes', 'No'] },
      { label: 'Do you have a local residence proof?', field: 'residence', type: 'select', options: ['Yes', 'No'] },
      { label: 'Are you registered with the local Gram Panchayat?', field: 'registered', type: 'select', options: ['Yes', 'No', 'Not sure'] },
    ],
    benefits: '100 days of guaranteed wage employment per year at the notified wage rate.',
    required_documents: ['Aadhaar card', 'Residence proof', 'Bank passbook', 'Photograph'],
    application_steps: [
      'Apply at the Gram Panchayat with identity and residence proof',
      'Get a Job Card issued (usually within 14 days)',
      'Demand work — the Panchayat must provide work within 15 days',
      'Receive wages directly into your bank account',
    ],
    official_source: 'MGNREGA',
    source_url: 'https://nrega.nic.in',
    last_verified: '2026-01-18',
    keywords: ['employment', 'job', 'rural', 'nrega', 'mgnrega', 'labour', 'wage', 'work', '100 days'],
  },
  {
    id: 'nsap',
    name: 'National Social Assistance Programme (NSAP)',
    ministry: 'Ministry of Rural Development',
    category: 'Pension',
    description:
      'Pension support for elderly (60+), widows, and persons with disabilities belonging to BPL families.',
    eligibility: [
      { label: 'What is your age?', field: 'age', type: 'number' },
      { label: 'Which category applies to you?', field: 'category', type: 'select', options: ['Elderly (60+)', 'Widow', 'Person with disability', 'None of these'] },
      { label: 'Are you from a BPL family?', field: 'bpl', type: 'select', options: ['Yes', 'No', 'Not sure'] },
      { label: 'What is your state of residence?', field: 'state', type: 'text' },
    ],
    benefits: 'Monthly pension of ₹200–500 (varies by state; some states add their own top-up).',
    required_documents: ['Aadhaar card', 'BPL certificate / ration card', 'Age proof (for elderly)', 'Death certificate of husband (for widow)', 'Disability certificate (for PwD)'],
    application_steps: [
      'Visit the Gram Panchayat / Municipality office',
      'Submit the application with required documents',
      'Get verified by the local authority',
      'Receive pension in your bank account',
    ],
    official_source: 'NSAP',
    source_url: 'https://nsap.nic.in',
    last_verified: '2026-01-14',
    keywords: ['pension', 'elderly', 'widow', 'disability', 'bpl', 'social assistance', 'senior citizen', 'old age'],
  },
  {
    id: 'pm-kisan',
    name: 'PM-KISAN (Kisan Samman Nidhi)',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'Agriculture',
    description:
      'Income support of ₹6,000 per year to all landholding farmer families in three installments.',
    eligibility: [
      { label: 'Do you own cultivable land?', field: 'land_ownership', type: 'select', options: ['Yes', 'No'] },
      { label: 'What is your occupation?', field: 'occupation', type: 'select', options: ['Farmer', 'Agricultural labour', 'Other'] },
      { label: 'Are you an institutional landholder (trust/company)?', field: 'institutional', type: 'select', options: ['No', 'Yes'] },
      { label: 'Are you a current or former government employee (Group A/B)?', field: 'govt_employee', type: 'select', options: ['No', 'Yes'] },
    ],
    benefits: '₹6,000 per year in three equal installments directly to the bank account.',
    required_documents: ['Aadhaar card', 'Land ownership records (patta/khata)', 'Bank passbook', 'Mobile number'],
    application_steps: [
      'Visit the PM-KISAN portal or a Common Service Centre',
      'Enter Aadhaar and land details',
      'Get verified by the local revenue officer',
      'Receive installments directly in your bank account',
    ],
    official_source: 'PM-KISAN',
    source_url: 'https://pmkisan.gov.in',
    last_verified: '2026-01-16',
    keywords: ['farmer', 'kisan', 'agriculture', 'pm-kisan', 'income support', 'land', 'cultivation'],
  },
  {
    id: 'sukanya',
    name: 'Sukanya Samriddhi Yojana',
    ministry: 'Ministry of Finance',
    category: 'Savings',
    description:
      'A savings scheme for the girl child under 10 years, offering high interest and tax benefits for her education and marriage.',
    eligibility: [
      { label: 'What is the age of the girl child?', field: 'girl_age', type: 'number' },
      { label: 'Is the girl child an Indian citizen?', field: 'citizen', type: 'select', options: ['Yes', 'No'] },
      { label: 'Has the account been opened before her 10th birthday?', field: 'opened_before_10', type: 'select', options: ['Yes', 'No', 'Not yet opened'] },
    ],
    benefits: 'High interest rate (declared quarterly); tax deduction under Section 80C; tax-free maturity.',
    required_documents: ['Girl child birth certificate', 'Parent ID proof', 'Address proof', 'Photograph'],
    application_steps: [
      'Visit a post office or authorized bank branch',
      'Submit the girl child birth certificate and parent documents',
      'Deposit the initial amount (minimum ₹250)',
      'Continue deposits until 15 years; account matures after 21 years',
    ],
    official_source: 'Sukanya Samriddhi Yojana',
    source_url: 'https://www.india.gov.in',
    last_verified: '2026-01-10',
    keywords: ['girl child', 'sukanya', 'savings', 'education', 'marriage', 'tax', 'scheme', 'daughter'],
  },
];
